name: Deploy react

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker image
        run: docker build -t marian/react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true marian/react-test npm run test
